theme: minima
title: Epic title
author: Me I guess
email: me@urmom.eu
description: > # this means to ignore newlines until "baseurl:"
 I are alcoholic

# social links
twitter_username: elonmusk # DO NOT include the @ character, or else the build will fail!
github_username:  gatesbill # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
